import { browserApiBase } from "./lib/browserApiBase";

/** Splash: logo draw, hold, lift, then disclaimer readable before login. */
export const SPLASH_DURATION_MS = Number(import.meta.env.VITE_SPLASH_DURATION_MS ?? 7200);

/**
 * User-facing Deep Scan slides. Indicator-by-indicator layers 2–10 duplicate the technical
 * carousel, so they are folded into the `technical` slide.
 *
 * `options_chain_greeks` is one slide because Full Document §5 is one section — a strike's
 * liquidity gates and its Greek verdict have to be read together, not two slides apart.
 */
export const SCAN_SLIDE_LAYERS = [
  "technical",
  "options_chain_greeks",
  "volatility",
  "sentiment",
  "fundamentals",
  "apex_score",
  "strategy",
  "risk_review",
] as const;

/** Slides that own the left/right arrow keys for their own internal card carousel. */
export const CAROUSEL_LAYERS: readonly string[] = ["technical", "options_chain_greeks", "volatility"];

export const API_BASE =
  typeof location !== "undefined"
    ? browserApiBase(import.meta.env.VITE_API_BASE_URL, location.origin)
    : (import.meta.env.VITE_API_BASE_URL ?? "");
export const WS_BASE =
  import.meta.env.VITE_WS_BASE_URL ??
  `${typeof location !== "undefined" && location.protocol === "https:" ? "wss" : "ws"}://${typeof location !== "undefined" ? location.host : "localhost:5173"}`;
export const DEFAULT_SYMBOL = "SPX";

// TODO(legal-review): disclaimer text pending legal review
export const DISCLAIMER_VERBATIM =
  "APEX's strategy outputs are algorithmic analyses, not personalized investment advice. APEX and its team are not registered as investment advisers or broker-dealers with the SEC or any state regulator. Nothing generated by this app is a recommendation to buy or sell any security or option. All trading decisions are made solely by the user, at the user's own risk, and APEX assumes no liability for any trading losses or other damages arising from use of this app.";

export const COPYRIGHT_VERBATIM = "© 2026 APEX. All Rights Reserved.";

export const EMA_PERIODS = [9, 21, 50, 100, 200] as const;
export const TIMEFRAMES = [
  { code: "1m", label: "1 Minute" },
  { code: "5m", label: "5 Minutes" },
  { code: "15m", label: "15 Minutes" },
  { code: "30m", label: "30 Minutes" },
  { code: "1H", label: "1 Hour" },
  { code: "4H", label: "4 Hours" },
  { code: "1D", label: "Daily" },
  { code: "1W", label: "Weekly" },
] as const;

/** Timeframe pills rendered inside the chart toolbar. */
export const CHART_TIMEFRAMES = TIMEFRAMES.map((t) => ({
  code: t.code,
  short: t.code === "1D" ? "D" : t.code === "1W" ? "W" : t.code.replace("1H", "1h").replace("4H", "4h"),
  label: t.label,
}));

export const PAPER_PRESETS = [10000, 25000, 50000, 100000] as const;

/**
 * Dashboard chart studies. Free TradingView Advanced Chart holds five study slots
 * (EMA 9, EMA 21, Bollinger 20/2, MACD pane, RSI pane) plus native volume; longer
 * EMAs are price-pane overlays (ChartOverlay). SuperTrend / Traditional pivots are
 * not drawn on the desk chart or scan snapshot.
 *
 * Enumerated from APEX docs — overlays named as chart studies:
 *   docs/APEX_Options_Platform_Full_Document.txt  §3.4 chart overlays, §4.2–4.8
 *   docs/Project_APEX.txt                         dashboard chart list + TA engine
 *   docs/DEEP_SCAN_LAYERS.md                      10-layer TA + THINK 10X
 *   docs/CONTRACT.md                              indicator parameters + volume A/D
 */

export const CHART_STUDY_LABELS = [
  "EMA 9",
  "EMA 21",
  "EMA 50",
  "EMA 100",
  "EMA 200",
  "SMA 20",
  "SMA 50",
  "SMA 200",
  "Bollinger 20/2",
  "MACD 12/26/9",
  "RSI 14",
  "Volume",
  "Accumulation/Distribution",
  "ATR 10",
  "Pivot High/Low (S/R)",
  "Volume Profile (S/R)",
] as const;

export const SNAPSHOT_STUDIES = [
  "EMA_9",
  "EMA_21",
  "EMA_50",
  "EMA_100",
  "EMA_200",
  "SMA_50",
  "SMA_200",
  "MACD_12_26_9",
  "RSI_14",
  "BOLLINGER_20_2",
  "VOLUME",
];

