from __future__ import annotations

from typing import Protocol

from app.schemas.market import Expiration, OptionChain, Quote, SearchHit


class MarketAdapter(Protocol):
    name: str
    feed: str

    async def search(self, query: str) -> list[SearchHit]: ...
    async def quote(self, symbol: str) -> Quote: ...
    async def bars(self, symbol: str, timeframe: str, limit: int = 180) -> list[dict]: ...
    async def expirations(self, symbol: str) -> list[Expiration]: ...
    async def option_chain(self, symbol: str, expiry: str) -> OptionChain: ...
    async def submit_order(self, **kwargs) -> dict: ...
